version: '3.8'
services:
  minecraft:
    image: openjdk:21-jdk
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - ${SERVER_DIR}:/server
    command: bash -c "cd /server/ && java -Xms${XMS} -Xmx${XMX} -jar ${JAR_FILE} nogui"
    deploy:
      mode: global
    stdin_open: true
    tty: true
    networks:
      - minecraft

networks:
  minecraft:
    external: true
