global:
  scrape_interval: 30s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
    metrics_path: '/prometheus/metrics'
    scheme: http
     

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
