global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090/prometheus']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
